### ISSUE TITLE
Unsupported major.minor version 52.0----am i missed something?

### ISSUE THREAD

**Issue by SeekPoint** [renmengye/imageqa-qgen#1]
rzai@rzai00:~/prj/imageqa-qgen$ python question_generator.py -parser_path stanford-parser-full-2015-12-09 -sentence "A man is riding a horse"
INFO: 2016-10-31 13:23:14 question_generator.py:1078 Single sentence mode
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/stanford/nlp/parser/lexparser/LexicalizedParser : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Traceback (most recent call last):
  File "question_generator.py", line 1079, in <module>
    runSentence(parserFolder=args.parser_path, sentence=args.sentence)
  File "question_generator.py", line 1031, in runSentence
    tree = parser.rootsList[0]
IndexError: list index out of range
rzai@rzai00:~/prj/imageqa-qgen$

**Comment by renmengye** [comment]
This is a Stanford Parser issue. You need to use standard JVM instead of OpenJVM.

**Comment by SeekPoint** [comment]
it can be fix by
upgrade openjdk from 1.7 to 1.8
